### ISSUE TITLE
Unable to resolve module '.src/utils/links'

### ISSUE THREAD

**Issue by Hannibal2** [TroddenSpade/LoAX#1]
Hello!
I want to run this app and exactly  after downloading I ran expo startand got this error...

**Comment by TroddenSpade** [comment]
@Hannibal2 thanks for downloading LoAX.
this app used to run on a server, links file contains server address and some other routes
I added [links](https://github.com/TroddenSpade/LoAX/blob/master/src/utils/links.js) to the project.
change the server address to 
`const SERVER = "http://localhost:3000";`
expo can build the app without any problem but LoAX only shows the loading screen becuase our server is down.

for testing LoAX and running server on your **localhost**, you can do the following steps
1. Clone [LoAX-server](https://github.com/TroddenSpade/LoAX-server)
2. Install dependencies `npm i`
Make sure to install mongoDB
3. run server `node server.js`
